//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigaPrvaka.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Igraci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Igraci()
        {
            this.Statistikas = new HashSet<Statistika>();
        }
    
        public int PKIgracID { get; set; }
        public string Ime { get; set; }
        public Nullable<int> FKTimID { get; set; }
    
        public virtual Timovi Timovi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Statistika> Statistikas { get; set; }
    }
}
