//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigaPrvaka.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistika
    {
        public Nullable<int> FKIgracID { get; set; }
        public Nullable<int> FKUtakmicaID { get; set; }
        public Nullable<int> Br_golova { get; set; }
        public int PKStatistikaID { get; set; }
    
        public virtual Igraci Igraci { get; set; }
        public virtual Utakmouse Utakmouse { get; set; }
    }
}
