//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigaPrvaka.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timovi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Timovi()
        {
            this.Igracis = new HashSet<Igraci>();
            this.Utakmice = new HashSet<Utakmouse>();
            this.Utakmice1 = new HashSet<Utakmouse>();
        }
    
        public int PKTimID { get; set; }
        public string Naziv { get; set; }
        public Nullable<int> Broj_igraca { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Igraci> Igracis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utakmouse> Utakmice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utakmouse> Utakmice1 { get; set; }
    }
}
