//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigaPrvaka.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utakmouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utakmouse()
        {
            this.Statistikas = new HashSet<Statistika>();
        }
    
        public int PKUtakmicaID { get; set; }
        public Nullable<int> Domaci { get; set; }
        public Nullable<int> Gosti { get; set; }
        public Nullable<int> Br_golova_d { get; set; }
        public Nullable<int> Br_golova_g { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Statistika> Statistikas { get; set; }
        public virtual Timovi Timovi { get; set; }
        public virtual Timovi Timovi1 { get; set; }
    }
}
